// Licensed to the Symphony Software Foundation (SSF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The SSF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
/* 
 * Pod API
 *
 * This document refers to Symphony API calls that do not need encryption or decryption of content.  - sessionToken can be obtained by calling the authenticationAPI on the symphony back end and the key manager respectively. Refer to the methods described in authenticatorAPI.yaml. - Actions are defined to be atomic, ie will succeed in their entirety or fail and have changed nothing. - If it returns a 40X status then it will have made no change to the system even if ome subset of the request would have succeeded. - If this contract cannot be met for any reason then this is an error and the response code will be 50X. 
 *
 * OpenAPI spec version: current
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace SymphonyOSS.RestApiClient.Generated.OpenApi.PodApi.Model
{
    /// <summary>
    /// list of streams info
    /// </summary>
    [DataContract]
    public partial class AdminStreamList :  IEquatable<AdminStreamList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdminStreamList" /> class.
        /// </summary>
        /// <param name="Count">total number of streams which match the filter criteria.</param>
        /// <param name="Skip">number of streams skipped.</param>
        /// <param name="Limit">maximum number of streams return.</param>
        /// <param name="Filter">filter criteria used in the request.</param>
        /// <param name="Streams">list of streams.</param>
        public AdminStreamList(long? Count = default(long?), int? Skip = default(int?), int? Limit = default(int?), AdminStreamFilter Filter = default(AdminStreamFilter), AdminStreamInfoList Streams = default(AdminStreamInfoList))
        {
            this.Count = Count;
            this.Skip = Skip;
            this.Limit = Limit;
            this.Filter = Filter;
            this.Streams = Streams;
        }
        
        /// <summary>
        /// total number of streams which match the filter criteria
        /// </summary>
        /// <value>total number of streams which match the filter criteria</value>
        [DataMember(Name="count", EmitDefaultValue=false)]
        public long? Count { get; set; }
        /// <summary>
        /// number of streams skipped
        /// </summary>
        /// <value>number of streams skipped</value>
        [DataMember(Name="skip", EmitDefaultValue=false)]
        public int? Skip { get; set; }
        /// <summary>
        /// maximum number of streams return
        /// </summary>
        /// <value>maximum number of streams return</value>
        [DataMember(Name="limit", EmitDefaultValue=false)]
        public int? Limit { get; set; }
        /// <summary>
        /// filter criteria used in the request
        /// </summary>
        /// <value>filter criteria used in the request</value>
        [DataMember(Name="filter", EmitDefaultValue=false)]
        public AdminStreamFilter Filter { get; set; }
        /// <summary>
        /// list of streams
        /// </summary>
        /// <value>list of streams</value>
        [DataMember(Name="streams", EmitDefaultValue=false)]
        public AdminStreamInfoList Streams { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdminStreamList {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Skip: ").Append(Skip).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Filter: ").Append(Filter).Append("\n");
            sb.Append("  Streams: ").Append(Streams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AdminStreamList);
        }

        /// <summary>
        /// Returns true if AdminStreamList instances are equal
        /// </summary>
        /// <param name="other">Instance of AdminStreamList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdminStreamList other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Count == other.Count ||
                    this.Count != null &&
                    this.Count.Equals(other.Count)
                ) && 
                (
                    this.Skip == other.Skip ||
                    this.Skip != null &&
                    this.Skip.Equals(other.Skip)
                ) && 
                (
                    this.Limit == other.Limit ||
                    this.Limit != null &&
                    this.Limit.Equals(other.Limit)
                ) && 
                (
                    this.Filter == other.Filter ||
                    this.Filter != null &&
                    this.Filter.Equals(other.Filter)
                ) && 
                (
                    this.Streams == other.Streams ||
                    this.Streams != null &&
                    this.Streams.Equals(other.Streams)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Count != null)
                    hash = hash * 59 + this.Count.GetHashCode();
                if (this.Skip != null)
                    hash = hash * 59 + this.Skip.GetHashCode();
                if (this.Limit != null)
                    hash = hash * 59 + this.Limit.GetHashCode();
                if (this.Filter != null)
                    hash = hash * 59 + this.Filter.GetHashCode();
                if (this.Streams != null)
                    hash = hash * 59 + this.Streams.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
